apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: masocp-cloud-credential-${RANDOM_STR}
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: ${SLS_INSTANCE_NAME}-aws-access
    namespace: ${SLS_NAMESPACE}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - effect: Allow
        action:
          - license-manager:CheckoutLicense
          - license-manager:GetLicense
          - license-manager:CheckInLicense
          - license-manager:ExtendLicenseConsumption
          - license-manager:ListReceivedLicenses
          - license-manager:GetLicenseUsage
        resource: "*"
